apiVersion: apps/v1
kind: Deployment
metadata:
  name: votacao-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votacao-frontend
  template:
    metadata:
      labels:
        app: votacao-frontend
    spec:
      containers:
      - name: votacao-frontend
        image: lucascorrea99/votacao-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: votacao-frontend
spec:
  type: NodePort
  selector:
    app: votacao-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020