---
name: votacao-ci/cd-dev
on:
  push:
    branches:
      - dev
jobs:
  build-dev:
    name: Build dev
    if: contains (github.ref, 'dev')
    runs-on: self-hosted
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u ${{ vars.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASS }}
    - name: acessar backend
      run: cd votacao-backend
    - name: monta imagem backend
      run: docker build -t lucascorrea99/votacao-backend:dev$GITHUB_SHA .
    - name: push imagem backend
      run: docker push lucascorrea99/votacao-backend:dev$GITHUB_SHA
    - name: acessar frontend  
      run: cd ../votacao-frontend
    - name: monta imagem frontend
      run: docker build -t lucascorrea99/votacao-frontend:dev$GITHUB_SHA .
    - name: push imagem frontend
      run: docker push lucascorrea99/votacao-frontend:dev$GITHUB_SHA
  test-dev:
    name: Test dev
    if: contains (github.ref, 'dev')
    runs-on: self-hosted
    needs: build-dev
    steps:
    - name: Step 1
      run: env
  deploy-dev:
    name: Deploy dev
    if: contains (github.ref, 'dev')
    runs-on: self-hosted
    needs: test-dev
    steps:
    - name: run command
      run: echo $GITHUB_SHA